/*      (c) COPYRIGHT 1988-1990 by Novell, Inc.  All Rights Reserved.   */
#ifndef _NIT_H
#define _NIT_H
/*______________________________________________________________
       This header is used to combine all other header files
       except for the SAP.H, NXT.H, DIAG.H, and 386 .h files
  ______________________________________________________________*/
#include <nwacct.h>
#include <nwbindry.h>
#include <nwconn.h>
#include <nwconsol.h>
#include <nwdir.h>
#include <nwfile.h>
#include <nwlocal.h>
#include <nwmisc.h>
#include <nwmsg.h>
#include <nwprint.h>
#include <nwsync.h>
#include <nwtts.h>
#include <nwwrkenv.h>

#endif
