#include <stdio.h>
////////////////////////////////////////////////////
int x,y;
typedef struct
        {
           int papa;
           int farinha;
        } bolo;
////////////////////////////////////////////////////
int soma(int a,int b)
{
   _cs=_ds=_ss;
   int c;
   float jose=0.00001;
   char chr='a';
   /*
      A vari vel chr n„o serve para nada.
   */
   c=a/b;
   c=a+b;
   return c;
   if (!bolo.papa) bolo.farinha++;
}
////////////////////////////////////////////////////
void main()
{
   double psp=0.;
   int *rato=.4;
   y=0;
   x = soma(10,y);
   printf("\n0x%04x",x);
}